// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUzC3sprWQCQfabHnZoZ8VGvTmkYEes0',
    appId: '1:839996709748:web:31f263a06b9a1483486a21',
    messagingSenderId: '839996709748',
    projectId: 'grocery-store-30daa',
    authDomain: 'grocery-store-30daa.firebaseapp.com',
    storageBucket: 'grocery-store-30daa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKyKVQCQmdowmecLQfJ6rPq5lTpcmgd0',
    appId: '1:839996709748:android:c7e01f4bb0c7d76c486a21',
    messagingSenderId: '839996709748',
    projectId: 'grocery-store-30daa',
    storageBucket: 'grocery-store-30daa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4K2WOo-x_qAJ7wwLC9AGpLFtizitwQc',
    appId: '1:839996709748:ios:3386ed59829c7f61486a21',
    messagingSenderId: '839996709748',
    projectId: 'grocery-store-30daa',
    storageBucket: 'grocery-store-30daa.appspot.com',
    iosClientId: '839996709748-bou82jnhfi2ugs7vg6l2k0bnspjh74uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR4K2WOo-x_qAJ7wwLC9AGpLFtizitwQc',
    appId: '1:839996709748:ios:3386ed59829c7f61486a21',
    messagingSenderId: '839996709748',
    projectId: 'grocery-store-30daa',
    storageBucket: 'grocery-store-30daa.appspot.com',
    iosClientId: '839996709748-bou82jnhfi2ugs7vg6l2k0bnspjh74uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryStore',
  );
}
